create table permissions (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table role_permissions (permission_id bigint not null, role_id bigint not null, primary key (permission_id, role_id)) engine=InnoDB;
create table roles (id bigint not null auto_increment, role_name enum ('ADMIN','DEVELOPER','INVITED','USER'), primary key (id)) engine=InnoDB;
create table user_contacts (contact_id bigint not null, user_id bigint not null, primary key (contact_id, user_id)) engine=InnoDB;
create table user_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
create table users (account_no_expired bit, account_no_locked bit, birthday date, credential_no_expired bit, done_favours integer not null, is_enabled bit, requested_favours integer not null, id bigint not null auto_increment, bio TEXT, interests TEXT, location varchar(255), name varchar(255), password varchar(255), picture varchar(255), surname varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table permissions add constraint UKpnvtwliis6p05pn6i3ndjrqt2 unique (name);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references permissions (id);
alter table role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references roles (id);
alter table user_contacts add constraint FKpv0xogldk4u85927p4492211j foreign key (contact_id) references users (id);
alter table user_contacts add constraint FKqgbpf3rh5b6i7npvr2rf776rd foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table permissions (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table role_permissions (permission_id bigint not null, role_id bigint not null, primary key (permission_id, role_id)) engine=InnoDB;
create table roles (id bigint not null auto_increment, role_name enum ('ADMIN','DEVELOPER','INVITED','USER'), primary key (id)) engine=InnoDB;
create table user_contacts (contact_id bigint not null, user_id bigint not null, primary key (contact_id, user_id)) engine=InnoDB;
create table user_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
create table users (account_no_expired bit, account_no_locked bit, birthday date, credential_no_expired bit, done_favours integer not null, is_enabled bit, requested_favours integer not null, id bigint not null auto_increment, bio TEXT, interests TEXT, location varchar(255), name varchar(255), password varchar(255), picture varchar(255), surname varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table permissions add constraint UKpnvtwliis6p05pn6i3ndjrqt2 unique (name);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references permissions (id);
alter table role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references roles (id);
alter table user_contacts add constraint FKpv0xogldk4u85927p4492211j foreign key (contact_id) references users (id);
alter table user_contacts add constraint FKqgbpf3rh5b6i7npvr2rf776rd foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table permissions (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table role_permissions (permission_id bigint not null, role_id bigint not null, primary key (permission_id, role_id)) engine=InnoDB;
create table roles (id bigint not null auto_increment, role_name enum ('ADMIN','DEVELOPER','INVITED','USER'), primary key (id)) engine=InnoDB;
create table user_contacts (contact_id bigint not null, user_id bigint not null, primary key (contact_id, user_id)) engine=InnoDB;
create table user_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
create table users (account_no_expired bit, account_no_locked bit, birthday date, credential_no_expired bit, done_favours integer not null, is_enabled bit, requested_favours integer not null, id bigint not null auto_increment, bio TEXT, interests TEXT, location varchar(255), name varchar(255), password varchar(255), picture varchar(255), surname varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table permissions add constraint UKpnvtwliis6p05pn6i3ndjrqt2 unique (name);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table role_permissions add constraint FKegdk29eiy7mdtefy5c7eirr6e foreign key (permission_id) references permissions (id);
alter table role_permissions add constraint FKn5fotdgk8d1xvo8nav9uv3muc foreign key (role_id) references roles (id);
alter table user_contacts add constraint FKpv0xogldk4u85927p4492211j foreign key (contact_id) references users (id);
alter table user_contacts add constraint FKqgbpf3rh5b6i7npvr2rf776rd foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
